# Modelos del esquema dbo
from .__efmigrationshistory import Efmigrationshistory
from .aautorizar import Aautorizar
from .accesos import Accesos
from .acomision import Acomision
from .addingsclientes import Addingsclientes
from .addingsproveedor import Addingsproveedor
from .adepreciacion import Adepreciacion
from .adistr import Adistr
from .admoncaja import Admoncaja
from .afp import Afp
from .agencia import Agencia
from .agrupaclientes import Agrupaclientes
from .almacen import Almacen
from .almnula import Almnula
from .almtaller import Almtaller
from .anivel import Anivel
from .anticipofactura import Anticipofactura
from .anticipos import Anticipos
from .aproducto import Aproducto
from .asegurad import Asegurad
from .asignafull import Asignafull
from .atipo import Atipo
from .autfact import Autfact
from .autocheque import Autocheque
from .autorizar import Autorizar
from .banco import Banco
from .bodega import Bodega
from .bodegapais import Bodegapais
from .bodeguero import Bodeguero
from .bomba import Bomba
from .bombatanque import Bombatanque
from .caccesos import Caccesos
from .caja import Caja
from .cajanotas import Cajanotas
from .cajatipomov import Cajatipomov
from .cajavendedor import Cajavendedor
from .cambioempleado import Cambioempleado
from .cambiogrupo import Cambiogrupo
from .cambiojornada import Cambiojornada
from .cambiojornadaemp import Cambiojornadaemp
from .cambnula import Cambnula
from .cambodega import Cambodega
from .camion import Camion
from .candidato import Candidato
from .cargaanticipo import Cargaanticipo
from .cargo import Cargo
from .cargoscomp import Cargoscomp
from .cargosfact import Cargosfact
from .cargosocomp import Cargosocomp
from .casaprod import Casaprod
from .categori import Categori
from .categoriabien import Categoriabien
from .categorianomina import Categorianomina
from .categoritaller import Categoritaller
from .ccontrato import Ccontrato
from .ccosto import Ccosto
from .checkcontrol import Checkcontrol
from .checkroom import Checkroom
from .chequerechazado import Chequerechazado
from .ciclo import Ciclo
from .cintaauditoria import Cintaauditoria
from .clase import Clase
from .clasificacion import Clasificacion
from .clidprodprec import Clidprodprec
from .cliencatego import Cliencatego
from .clientedatos import Clientedatos
from .clienteformula import Clienteformula
from .clientes import Clientes
from .clientes_caja import ClientesCaja
from .clientesdocs import Clientesdocs
from .clientesgrupo import Clientesgrupo
from .clientesmod import Clientesmod
from .cliprodprec import Cliprodprec
from .coddepto import Coddepto
from .codmunicip import Codmunicip
from .comision import Comision
from .comisionagencia import Comisionagencia
from .comisiontienda import Comisiontienda
from .comisionventas import Comisionventas
from .compnula import Compnula
from .compra import Compra
from .comprafirme import Comprafirme
from .compras import Compras
from .conceptodiezmo import Conceptodiezmo
from .conciliabancos import Conciliabancos
from .conciliado import Conciliado
from .condpago import CondPago
from .consigna import Consigna
from .contingencia import Contingencia
from .contnula import Contnula
from .contrato import Contrato
from .contratoabono import Contratoabono
from .contratopagos import Contratopagos
from .controla import Controla
from .controlcaja import Controlcaja
from .controlcarga import Controlcarga
from .controlcitas import Controlcitas
from .controlcorrel import Controlcorrel
from .controlcosto import Controlcosto
from .controldia import Controldia
from .controles import Controles
from .controlperiodo import ControlPeriodo
from .controlregistro import Controlregistro
from .controlsolicitud import Controlsolicitud
from .controltramo import Controltramo
from .controlvence import Controlvence
from .controlvineta import Controlvineta
from .corrcotiza import Corrcotiza
from .corrdiezmo import Corrdiezmo
from .correlativos import Correlativos
from .costotipo import Costotipo
from .cotifactura import Cotifactura
from .cotiremision import Cotiremision
from .cotizacion import Cotizacion
from .cpagocompra import Cpagocompra
from .cpartida import Cpartida
from .cprodprec import Cprodprec
from .ctactrocto import Ctactrocto
from .ctalong import Ctalong
from .ctcategori import Ctcategori
from .ctracking import Ctracking
from .ctrocosto import Ctrocosto
from .ctrolong import Ctrolong
from .cuenta import Cuenta
from .cuentaclave import Cuentaclave
from .cuentapuente import Cuentapuente
from .cuentatipomov import Cuentatipomov
from .cxp import Cxp
from .dafp import Dafp
from .dalmacen import Dalmacen
from .dalmacennc import Dalmacennc
from .datoscomision import Datoscomision
from .dbudget import Dbudget
from .dcambio import Dcambio
from .dcambodega import DCamboBodega
from .dcargaanticipo import Dcargaanticipo
from .dcompra import Dcompra
from .dcompranc import Dcompranc
from .dconciliado import Dconciliado
from .dcontrato import Dcontrato
from .dcontrola import Dcontrola
from .dcontrolcarga import Dcontrolcarga
from .dcontrolvence import Dcontrolvence
from .dcpartida import Dcpartida
from .dcprodprec import Dcprodprec
from .dcuenta import Dcuenta
from .ddiezmo import Ddiezmo
from .decimotercero import Decimotercero
from .depend import Depend
from .depto import Depto
from .descmax import Descmax
from .detallecotizacion import Detallecotizacion
from .detallepago import Detallepago
from .dfactmes import Dfactmes
from .dfactura import DFactura
from .dfliquida import Dfliquida
from .dformulataller import Dformulataller
from .dfpartida import Dfpartida
from .dgestiontaller import Dgestiontaller
from .dgetcompra import Dgetcompra
from .diaferiado import Diaferiado
from .diaslaborados import Diaslaborados
from .diezmo import Diezmo
from .dimpuesto import Dimpuesto
from .distrito import Distrito
from .dlinea1 import Dlinea1
from .dlinea2 import Dlinea2
from .dlpartida import Dlpartida
from .dmaestro import Dmaestro
from .docliente import Docliente
from .docompra import Docompra
from .docompra1 import Docompra1
from .docrecibido import Docrecibido
from .document import Document
from .documentoviaje import Documentoviaje
from .dofactura import Dofactura
from .donacion import Donacion
from .dordentrabajo import Dordentrabajo
from .doventa import Doventa
from .doventafact import Doventafact
from .dpagooing import Dpagooing
from .dpagos import Dpagos
from .dpartida import Dpartida
from .dpedidoalmacen import Dpedidoalmacen
from .dpentrega import Dpentrega
from .dperiodo import Dperiodo
from .dpfactura import Dpfactura
from .dplanilla import Dplanilla
from .dpoldesc import Dpoldesc
from .dpolingpla import Dpolingpla
from .dpolpladeduc import Dpolpladeduc
from .dppagos import Dppagos
from .dppartida import Dppartida
from .dpreciovineta import Dpreciovineta
from .dpreparar import Dpreparar
from .dpreped import Dpreped
from .dprestamo import Dprestamo
from .dproddevolucion import Dproddevolucion
from .dprodentregado import Dprodentregado
from .dprodprec import DProdPrec
from .dproducto import Dproducto
from .drecvineta import Drecvineta
from .dregciclo import Dregciclo
from .dregfactnula import Dregfactnula
from .dregllave import Dregllave
from .dregpagos import Dregpagos
from .dreporte import Dreporte
from .drliquida import Drliquida
from .drutacobro import Drutacobro
from .dte import Dte
from .dtipobudget import Dtipobudget
from .dtomafisica import Dtomafisica
from .dtranspte import Dtranspte
from .empleado import Empleado
from .empleadoregistro import Empleadoregistro
from .empresa import Empresa
from .emptipla import Emptipla
from .encompra import Encompra
from .entradabodega import Entradabodega
from .entrega import Entrega
from .entregable import Entregable
from .envio import Envio
from .enviocotiza import Enviocotiza
from .enviofactura import Enviofactura
from .equipo import Equipo
from .equipoprocess import Equipoprocess
from .estado import Estado
from .estatus import Estatus
from .estcivil import Estcivil
from .estilo import Estilo
from .etapa import Etapa
from .existen import Existen
from .fabricacion import Fabricacion
from .factcont import FactCont
from .factdelivery import Factdelivery
from .factelec import FactElec
from .factnula import Factnula
from .factorxcli import Factorxcli
from .factorxfact import Factorxfact
from .factpagos import Factpagos
from .factura import Factura
from .facturapago import Facturapago
from .facturapagos import Facturapagos
from .facturasexpress import Facturasexpress
from .factvehiculo import Factvehiculo
from .faltofacturar import Faltofacturar
from .fase import Fase
from .fbodega import Fbodega
from .feldata import Feldata
from .ffgasto import Ffgasto
from .fgasto import Fgasto
from .fgrupo import Fgrupo
from .fixed import Fixed
from .fmodelo import Fmodelo
from .formapago import FormaPago
from .formatonominas import Formatonominas
from .formpago import FormPago
from .formula import Formula
from .formulataller import Formulataller
from .foto import Foto
from .fpartida import Fpartida
from .fproducto import Fproducto
from .franjahoraria import Franjahoraria
from .frecpago import Frecpago
from .fruta import Fruta
from .ftablapart import Ftablapart
from .ftipoprod import Ftipoprod
from .garantia import Garantia
from .gastoanticipo import Gastoanticipo
from .gestiontaller import Gestiontaller
from .getcompra import Getcompra
from .giro import Giro
from .grupo import Grupo
from .grupoempleado import Grupoempleado
from .hinvkardex import Hinvkardex
from .historenta import Historenta
from .historiconomina import Historiconomina
from .horario import Horario
from .horasextras import Horasextras
from .idcaller import Idcaller
from .idtimecaller import Idtimecaller
from .impresor import Impresor
from .impuesto import Impuesto
from .impvineta import Impvineta
from .incapacidad import Incapacidad
from .infobanco import Infobanco
from .ingesp import Ingesp
from .ingfijo import Ingfijo
from .ingreso import Ingreso
from .insertpartida import Insertpartida
from .interes import Interes
from .intervaldesc import Intervaldesc
from .intervalopauta import Intervalopauta
from .invcliente import Invcliente
from .invkardex import Invkardex
from .invoct import Invoct
from .invpago import Invpago
from .iva import Iva
from .iva05 import Iva05
from .jornada import Jornada
from .jornadaruta import Jornadaruta
from .kardex import Kardex
from .kardex_caja import KardexCaja
from .kclientes import Kclientes
from .kcodbarra import Kcodbarra
from .kcuenta import Kcuenta
from .kproducto import Kproducto
from .ldpagos import Ldpagos
from .lecturabanco import Lecturabanco
from .lecturabodega import Lecturabodega
from .lecturabomba import Lecturabomba
from .letras import Letras
from .lider import Lider
from .lote import Lote
from .lpagos import Lpagos
from .lpagosnula import Lpagosnula
from .lpartida import Lpartida
from .maestros import Maestros
from .marca import Marca
from .marcavehiculo import Marcavehiculo
from .material import Material
from .mescompleto import Mescompleto
from .meses import Meses
from .mform983 import Mform983
from .mformprod import Mformprod
from .mformula import Mformula
from .mialmacenmov import Mialmacenmov
from .mibaseflujo import Mibaseflujo
from .micartera import Micartera
from .micolor import Micolor
from .midia import Midia
from .midsemana import Midsemana
from .miempleado import Miempleado
from .mifecha import Mifecha
from .miflujoproy import Miflujoproy
from .mikardex import Mikardex
from .mimensaje import Mimensaje
from .miperiodo import Miperiodo
from .miplan import Miplan
from .miprecio import Miprecio
from .miscompras import Miscompras
from .misfinanzas import Misfinanzas
from .misnopagos import Misnopagos
from .mispagos import Mispagos
from .misventas import Misventas
from .modulo import Modulo
from .moneda import Moneda
from .motorista import Motorista
from .movimiento import Movimiento
from .movkardex import Movkardex
from .municip import Municip
from .nacional import Nacional
from .naturaleza import Naturaleza
from .ncpedido import Ncpedido
from .ncv import Ncv
from .nivel import Nivel
from .nmicontrol import Nmicontrol
from .nochpedido import Nochpedido
from .nocpedido import Nocpedido
from .nominacliente import Nominacliente
from .nopedido import Nopedido
from .ocompra import Ocompra
from .ocomprafirme import Ocomprafirme
from .ocultabodega import Ocultabodega
from .ofactura import Ofactura
from .office import Office
from .oldprec import Oldprec
from .ordenformula import Ordenformula
from .ordentrabajo import Ordentrabajo
from .order import Order
from .order_detail import OrderDetail
from .oventa import Oventa
from .pagocomision import Pagocomision
from .pagocompra import Pagocompra
from .pagom3 import Pagom3
from .pagos import Pagos
from .pagosnula import Pagosnula
from .pais import Pais
from .parentes import Parentes
from .partida import Partida
from .partidavta import Partidavta
from .patrono import Patrono
from .pedido import Pedido
from .pedidoalmacen import Pedidoalmacen
from .pedidos import Pedidos
from .pentrega import Pentrega
from .perfilaccesos import Perfilaccesos
from .perfilusuario import Perfilusuario
from .periodo import Periodo
from .periodoactivo import Periodoactivo
from .periodocomision import Periodocomision
from .periodoiva import Periodoiva
from .periodopago import Periodopago
from .permisos import Permisos
from .perpla import Perpla
from .pfactura import Pfactura
from .pieza import Pieza
from .plandescuento import Plandescuento
from .planempty import Planempty
from .planilla import Planilla
from .planillareloj import Planillareloj
from .planingreso import Planingreso
from .planprestamo import Planprestamo
from .planwork import Planwork
from .plaperio import Plaperio
from .pncv import Pncv
from .pnopedido import Pnopedido
from .poldesc import Poldesc
from .polingpla import Polingpla
from .politing import Politing
from .politpla import Politpla
from .polpladeduc import Polpladeduc
from .ppagos import Ppagos
from .ppartida import Ppartida
from .preciovineta import Preciovineta
from .preparajornada import Preparajornada
from .preparapedido import Preparapedido
from .prepararemision import Prepararemision
from .preped import Preped
from .presenta import Presenta
from .presociales import Presociales
from .prestemp import Prestemp
from .proceso import Proceso
from .prodentregado import Prodentregado
from .prodform import Prodform
from .prodorden import Prodorden
from .prodplanta import Prodplanta
from .prodprec import ProdPrec
from .prodprectipcli import Prodprectipcli
from .producto import Producto
from .productounidadventa import Productounidadventa
from .profesion import Profesion
from .proveedor import Proveedor
from .provisiongasto import Provisiongasto
from .proyecto import Proyecto
from .ptovta import Ptovta
from .quienprepara import Quienprepara
from .rangocliente import Rangocliente
from .rangospagados import Rangospagados
from .razoncuenta import Razoncuenta
from .razonfinan import Razonfinan
from .rcontrol import Rcontrol
from .rdte import Rdte
from .recintofiscal import Recintofiscal
from .recordar import Recordar
from .recvineta import Recvineta
from .reffecha import Reffecha
from .regciclo import Regciclo
from .registrocontrol import Registrocontrol
from .registrogarantia import Registrogarantia
from .registroproducto import Registroproducto
from .regpagos import Regpagos
from .reloj import Reloj
from .remesa import Remesa
from .remesaagencia import Remesaagencia
from .repo import Repo
from .report import Report
from .reportcolumna import Reportcolumna
from .reporte import Reporte
from .reportheader import Reportheader
from .retencion import Retencion
from .rliquida import Rliquida
from .roles import Roles
from .rollonum import Rollonum
from .room import Room
from .rpdimpuesto import Rpdimpuesto
from .rpimpuesto import Rpimpuesto
from .rubro import Rubro
from .rupactividad import Rupactividad
from .rupcomponente import Rupcomponente
from .rupentregable import Rupentregable
from .rupfase import Rupfase
from .rupot import Rupot
from .rupotkardex import Rupotkardex
from .ruppersonal import Ruppersonal
from .rupsolicitud import Rupsolicitud
from .rupstandar import Rupstandar
from .rupstandarcontrol import Rupstandarcontrol
from .rupstatus import Rupstatus
from .rupsubactivitie import Rupsubactivitie
from .ruptipoactividad import Ruptipoactividad
from .ruptipoproceso import Ruptipoproceso
from .ruta import Ruta
from .rutacamion import Rutacamion
from .rutacobro import Rutacobro
from .rutapagos import Rutapagos
from .sacceso import Sacceso
from .saldocliente import Saldocliente
from .seccion import Seccion
from .sectorlaboral import Sectorlaboral
from .sexo import Sexo
from .sgzrdy import Sgzrdy
from .sheetwork import Sheetwork
from .solicitaautoriza import Solicitaautoriza
from .subproyecto import Subproyecto
from .sucursal import Sucursal
from .tablacomisiones import Tablacomisiones
from .talla import Talla
from .tamanopauta import Tamanopauta
from .tarea import Tarea
from .tdespacho import Tdespacho
from .temporada import Temporada
from .tiempococina import Tiempococina
from .tipcli import TipCli
from .tipcuenta import Tipcuenta
from .tipobodega import Tipobodega
from .tipobudget import Tipobudget
from .tipocargo import Tipocargo
from .tipocta import Tipocta
from .tipodato import Tipodato
from .tipodatoread import Tipodatoread
from .tipodatotxt import Tipodatotxt
from .tipoefectivo import Tipoefectivo
from .tipoescala import Tipoescala
from .tipogasto import Tipogasto
from .tipoincapacidad import Tipoincapacidad
from .tipomov import TipoMov
from .tipopago import Tipopago
from .tipopart import Tipopart
from .tipopedido import Tipopedido
from .tipopla import Tipopla
from .tipoplaza import Tipoplaza
from .tipoprest import Tipoprest
from .tipoprod import TipoProd
from .tipoprov import Tipoprov
from .tiposan import Tiposan
from .tiposeg import Tiposeg
from .tipovehiculo import Tipovehiculo
from .tipoviaje import Tipoviaje
from .tipovta import TipoVta
from .tipvende import Tipvende
from .tmovkardex import Tmovkardex
from .tmpkardex import Tmpkardex
from .tmpmikardex import Tmpmikardex
from .tmpproducto import Tmpproducto
from .tocompra import Tocompra
from .todos import Todos
from .tomafisica import Tomafisica
from .tpfactura import Tpfactura
from .transnopedido import Transnopedido
from .transpte import Transpte
from .turno import Turno
from .ubicaprod import UbicaProd
from .umedida import UMedida
from .unidad import Unidad
from .unidadventa import Unidadventa
from .useridentities import Useridentities
from .usuario import Usuario
from .usuarioempresa import Usuarioempresa
from .usuarioseccion import Usuarioseccion
from .vcontabilidad import Vcontabilidad
from .vendclien import Vendclien
from .vendedor import Vendedor
from .ventascc import Ventascc
from .ventascon import Ventascon
from .vretencion import Vretencion
from .xdte import Xdte
from .zona import Zona
from .zonavendedor import Zonavendedor
