# Generado automáticamente
# Tabla: dbo.cambodega
# Fecha: 2025-05-13 16:44:58

from ..base import Base
from sqlalchemy import Column, Boolean
from sqlalchemy import Column, DateTime
from sqlalchemy import Column, Float
from sqlalchemy import Column, Integer
from sqlalchemy import Column, Numeric
from sqlalchemy import Column, String
# from sqlalchemy.orm import relationship  # Comentado temporalmente


class Cambodega(Base):
    __tablename__ = "cambodega"
    __table_args__ = {"schema": "dbo"}

    activo = Column(Boolean, nullable=False)
    tipomov = Column(Integer, nullable=False)
    numedocu = Column(String(9), nullable=False)
    fecha = Column(DateTime, nullable=False)
    impresa = Column(Boolean, nullable=False)
    nula = Column(Boolean, nullable=False)
    notas = Column(String(150), nullable=False)
    moneda = Column(Integer, nullable=False)
    tasacambio = Column(Numeric(16, 6), nullable=False)
    tasacambioseg = Column(Numeric(16, 6), nullable=False)
    tasacambiotres = Column(Numeric(16, 6), nullable=False)
    cambodega = Column(Integer, primary_key=True, nullable=False, autoincrement=True)
    empresa = Column(Integer, nullable=False)
    usuario = Column(Integer, nullable=False)
    horatiempo = Column(DateTime, nullable=False)
    clientes = Column(String(25), nullable=False)
    vendedor = Column(Integer, nullable=False)
    docunico = Column(String(9), nullable=False)
    EXENTA = Column(Numeric(18, 6), nullable=False)
    AFECTA = Column(Numeric(18, 6), nullable=False)
    VIVA = Column(Numeric(18, 6), nullable=False)
    MONTFACT = Column(Numeric(18, 6), nullable=False)
    RETENCION = Column(Numeric(18, 6), nullable=False)
    condpago = Column(Integer, nullable=False)
    percepcion = Column(Numeric(18, 6), nullable=False)
    nosujeto = Column(Numeric(18, 6), nullable=False)
    bodegas = Column(Integer, nullable=False)
    bodega = Column(Integer, nullable=False)
    fdevolucion1 = Column(DateTime)
    fdevolucion2 = Column(DateTime)
    fdevolucion3 = Column(DateTime)
    fdevolucion4 = Column(DateTime)
    fdevolucion5 = Column(DateTime)
    entregado = Column(Boolean, nullable=False)
    factura = Column(Integer, nullable=False)
    camion = Column(Integer, nullable=False)
    transpte = Column(Integer, nullable=False)
    motorista = Column(Integer, nullable=False)
    precio = Column(Numeric(18, 6), nullable=False)
    producto = Column(Integer, nullable=False)
    numtiquet = Column(Integer, nullable=False)
    preparaJornada = Column(Integer, nullable=False)
    fnumtiquet = Column(Integer, nullable=False)
    nInicial = Column(String(12), nullable=False)
    nFinal = Column(String(12), nullable=False)
    liquidada = Column(Boolean, nullable=False)
    factorInteres = Column(Integer, nullable=False)
    pprima = Column(Numeric(18, 6), nullable=False)
    letras = Column(Integer, nullable=False)
    cuotas = Column(Numeric(18, 6), nullable=False)
    diapago = Column(Integer, nullable=False)
    fechainicial = Column(DateTime, nullable=False)
    montocredito = Column(Numeric(18, 6), nullable=False)
    procesado = Column(Boolean, nullable=False)
    pais = Column(Integer)
    PrecioActualizado = Column(Boolean, nullable=False)
    prodprec = Column(Integer, nullable=False)
    caja = Column(Integer, nullable=False)
    ofactura = Column(Integer, nullable=False)
    cambodegareferencia = Column(Integer, nullable=False)
    enfirme = Column(Boolean, nullable=False)
    enruta = Column(Boolean, nullable=False)
    impBod = Column(Boolean, nullable=False)
    estado = Column(Integer, nullable=False)
    dev1 = Column(String(9))
    dev2 = Column(String(9))
    dev3 = Column(String(9))
    dev4 = Column(String(9))
    dev5 = Column(String(9))
    vendedor1 = Column(Integer)
    vendedor2 = Column(Integer)
    vendedor3 = Column(Integer)
    vendedor4 = Column(Integer)
    vendedor5 = Column(Integer)
    motivo1 = Column(Integer, nullable=False)
    motivo2 = Column(Integer, nullable=False)
    motivo3 = Column(Integer, nullable=False)
    motivo4 = Column(Integer, nullable=False)
    motivo5 = Column(Integer, nullable=False)
    fdevolucion6 = Column(DateTime)
    fdevolucion7 = Column(DateTime)
    fdevolucion8 = Column(DateTime)
    fdevolucion9 = Column(DateTime)
    fdevolucion10 = Column(DateTime)
    fdevolucion11 = Column(DateTime)
    fdevolucion12 = Column(DateTime)
    fdevolucion13 = Column(DateTime)
    fdevolucion14 = Column(DateTime)
    fdevolucion15 = Column(DateTime)
    dev6 = Column(String(9))
    dev7 = Column(String(9))
    dev8 = Column(String(9))
    dev9 = Column(String(9))
    dev10 = Column(String(9))
    dev11 = Column(String(9))
    dev12 = Column(String(9))
    dev13 = Column(String(9))
    dev14 = Column(String(9))
    dev15 = Column(String(9))
    vendedor6 = Column(Integer)
    vendedor7 = Column(Integer)
    vendedor8 = Column(Integer)
    vendedor9 = Column(Integer)
    vendedor10 = Column(Integer)
    vendedor11 = Column(Integer)
    vendedor12 = Column(Integer)
    vendedor13 = Column(Integer)
    vendedor14 = Column(Integer)
    vendedor15 = Column(Integer)
    fechafin = Column(DateTime)
    fechacancela = Column(DateTime)
    propina = Column(Float)
    nombre = Column(String(50))
    casaprod = Column(Integer)

    # Relaciones
    # tipomov_rel = relationship("Tipomov", back_populates="cambodega_set")  # Comentado automáticamente

    def __repr__(self):
        return "<Cambodega(cambodega={self.cambodega})>"