# Generado automáticamente
# Tabla: dbo.clientesmod
# Fecha: 2025-05-13 16:44:58

from ..base import Base
from sqlalchemy import Column, Boolean
from sqlalchemy import Column, DateTime
from sqlalchemy import Column, Integer
from sqlalchemy import Column, Numeric
from sqlalchemy import Column, String
# from sqlalchemy.orm import relationship  # Comentado temporalmente


class Clientesmod(Base):
    __tablename__ = "clientesmod"
    __table_args__ = {"schema": "dbo"}

    nclientes = Column(String(60), nullable=False)
    propietario = Column(String(50), nullable=False)
    moneda = Column(Integer, nullable=False)
    tipcli = Column(Integer, nullable=False)
    municip = Column(Integer, nullable=False)
    transpte = Column(Integer, nullable=False)
    condpago = Column(Integer, nullable=False)
    prodprec = Column(Integer, nullable=False)
    cliencatego = Column(Integer, nullable=False)
    contado = Column(Boolean, nullable=False)
    contacto = Column(String(50), nullable=False)
    direccion = Column(String(200), nullable=False)
    recomendado = Column(String(120), nullable=False)
    activo = Column(Boolean, nullable=False)
    razonsoc = Column(String(50), nullable=False)
    registro = Column(String(15), nullable=False)
    giro = Column(String(50), nullable=False)
    nit = Column(String(20))
    telefono1 = Column(String(25))
    telefono2 = Column(String(15), nullable=False)
    celular = Column(String(15), nullable=False)
    fax = Column(String(15), nullable=False)
    exento = Column(Boolean, nullable=False)
    descuento = Column(Integer, nullable=False)
    email = Column(String(50), nullable=False)
    promcomp = Column(Numeric(16, 6), nullable=False)
    prompago = Column(Numeric(16, 6), nullable=False)
    limitecredito = Column(Numeric(16, 6), nullable=False)
    saldo = Column(String(10), nullable=False)
    hora = Column(DateTime, nullable=False)
    notas = Column(String(250), nullable=False)
    clientes = Column(String(25), primary_key=True, nullable=False)
    empresa = Column(Integer, nullable=False)
    usuario = Column(Integer, nullable=False)
    horatiempo = Column(DateTime, nullable=False)
    retencion = Column(Boolean, nullable=False)
    contrato = Column(Boolean, nullable=False)
    nacimiento = Column(DateTime)
    casa = Column(String(200), nullable=False)
    telecasa = Column(String(15), nullable=False)
    trabajo = Column(String(200), nullable=False)
    cargo = Column(String(20), nullable=False)
    profesion = Column(String(20), nullable=False)
    teletrabajo = Column(String(15), nullable=False)
    direcciont = Column(String(200), nullable=False)
    fuente1 = Column(String(20), nullable=False)
    ing1 = Column(String(10), nullable=False)
    firma = Column(String(100), nullable=False)
    sueldo1 = Column(String(10), nullable=False)
    gastos1 = Column(String(10), nullable=False)
    conyuge = Column(String(150), nullable=False)
    dui = Column(String(20), nullable=False)
    sueldo2 = Column(String(10), nullable=False)
    trabajo2 = Column(String(100), nullable=False)
    teletrabajo2 = Column(String(15), nullable=False)
    gastos2 = Column(String(10), nullable=False)
    tel1 = Column(String(15), nullable=False)
    referencia1 = Column(String(100), nullable=False)
    relacion1 = Column(String(20), nullable=False)
    referencia2 = Column(String(100), nullable=False)
    tel2 = Column(String(15), nullable=False)
    relacion2 = Column(String(20), nullable=False)
    referencia3 = Column(String(100), nullable=False)
    tel3 = Column(String(15), nullable=False)
    relacion3 = Column(String(100), nullable=False)
    referencia4 = Column(String(100), nullable=False)
    tel4 = Column(String(15), nullable=False)
    relacion4 = Column(String(100), nullable=False)
    notas2 = Column(String(200), nullable=False)
    ivacero = Column(Boolean, nullable=False)
    PROPIO = Column(Boolean, nullable=False)
    PDESC = Column(Numeric(5, 2), nullable=False)
    ZONA = Column(Integer, nullable=False)
    pApellido = Column(String(50))
    sApellido = Column(String(50))
    Nombres = Column(String(50))
    bodega = Column(Integer, nullable=False)
    MESA = Column(Boolean)
    NOPROPINA = Column(Boolean)
    referido = Column(String(25), nullable=False)
    direnvio = Column(String(250), nullable=False)
    agrupaclientes = Column(Integer, nullable=False)
    vendedor = Column(Integer, nullable=False)
    preciovineta = Column(Integer, nullable=False)
    percepcion = Column(Boolean, nullable=False)
    nosujeto = Column(Boolean, nullable=False)
    comisionagencia = Column(Numeric(18, 6), nullable=False)
    CargoFULL = Column(Boolean, nullable=False)
    marchamo = Column(Boolean, nullable=False)
    vendedor2 = Column(Integer, nullable=False)
    pais = Column(Integer, nullable=False)
    idClientes = Column(Integer, nullable=False, autoincrement=True)
    autoconsumo = Column(Boolean, nullable=False)
    gobierno = Column(Boolean, nullable=False)
    cuenta = Column(Integer, nullable=False)
    cuentaProveedor = Column(Integer, nullable=False)
    ExcluirCredito = Column(Boolean, nullable=False)
    conPagare = Column(Boolean, nullable=False)
    Verificado = Column(Boolean, nullable=False)
    descEspecial = Column(Boolean, nullable=False)
    valorreferencia1 = Column(Integer, nullable=False)
    valorreferencia2 = Column(Integer, nullable=False)
    valorreferencia3 = Column(Integer, nullable=False)
    valorreferencia4 = Column(Integer, nullable=False)
    noPagare = Column(String(12), nullable=False)
    fechaPagare = Column(DateTime)
    vencePagare = Column(DateTime)
    montoPagare = Column(Numeric(18, 6))
    PagareAbierto = Column(Integer)
    firmaFactura = Column(Boolean)
    endipcom = Column(Boolean)
    tweeter = Column(String(35), nullable=False)
    facebook = Column(String(35), nullable=False)
    celular2 = Column(String(15), nullable=False)
    celular3 = Column(String(15), nullable=False)
    direccioncobro = Column(String(250), nullable=False)
    ordenRuta = Column(String(5), nullable=False)
    montoref1 = Column(Numeric(18, 6), nullable=False)
    montoref2 = Column(Numeric(18, 6), nullable=False)
    montoref3 = Column(Numeric(18, 6), nullable=False)
    montoref4 = Column(Numeric(18, 6), nullable=False)
    foda = Column(String(500))

    # Relaciones
    # cliencatego_rel = relationship("Cliencatego", back_populates="clientesmod_set")  # Comentado automáticamente
    # prodprec_rel = relationship("Prodprec", back_populates="clientesmod_set")  # Comentado automáticamente
    # tipcli_rel = relationship("Tipcli", back_populates="clientesmod_set")  # Comentado automáticamente

    def __repr__(self):
        return "<Clientesmod(clientes={self.clientes})>"