# Generado automáticamente
# Tabla: dbo.dpfactura
# Fecha: 2025-05-13 16:44:58

from ..base import Base
from sqlalchemy import Column, Boolean
from sqlalchemy import Column, DateTime
from sqlalchemy import Column, Integer
from sqlalchemy import Column, Numeric
from sqlalchemy import Column, String
# from sqlalchemy.orm import relationship  # Comentado temporalmente


class Dpfactura(Base):
    __tablename__ = "dpfactura"
    __table_args__ = {"schema": "dbo"}

    activo = Column(Boolean, nullable=False)
    cantidad = Column(Numeric(16, 6), nullable=False)
    reservado = Column(Numeric(16, 6), nullable=False)
    gratificado = Column(Numeric(16, 6), nullable=False)
    bonificado = Column(Numeric(16, 6), nullable=False)
    hcantidad = Column(Numeric(16, 6), nullable=False)
    hreservado = Column(Numeric(16, 6), nullable=False)
    hgratificado = Column(Numeric(16, 6), nullable=False)
    hbonificado = Column(Numeric(16, 6), nullable=False)
    precio = Column(Numeric(16, 6), nullable=False)
    preciolist = Column(Numeric(16, 6), nullable=False)
    montfact = Column(Numeric(16, 6), nullable=False)
    afecta = Column(Numeric(16, 6), nullable=False)
    exenta = Column(Numeric(16, 6), nullable=False)
    viva = Column(Numeric(16, 6), nullable=False)
    texto = Column(String(10), nullable=False)
    pdesc = Column(Numeric(16, 6), nullable=False)
    vdesc = Column(Numeric(16, 6), nullable=False)
    vgdesc = Column(Numeric(16, 6), nullable=False)
    factura = Column(Integer, nullable=False)
    kardex = Column(Integer, nullable=False)
    costo = Column(Numeric(16, 6), nullable=False)
    dpfactura = Column(Integer, primary_key=True, nullable=False, autoincrement=True)
    empresa = Column(Integer, nullable=False)
    usuario = Column(Integer, nullable=False)
    horatiempo = Column(DateTime, nullable=False)
    fovial = Column(Numeric(16, 6), nullable=False)
    pfactura = Column(Integer, nullable=False)
    cantidadfact = Column(Numeric(16, 6), nullable=False)
    enfirme = Column(Boolean, nullable=False)
    nombre = Column(String(1000))
    nula = Column(Boolean, nullable=False)
    oPrecio = Column(Numeric(18, 6), nullable=False)
    motorista = Column(Integer, nullable=False)
    camion = Column(Integer, nullable=False)
    estatus = Column(Integer, nullable=False)
    fechaentrega = Column(DateTime)
    fechainicio = Column(DateTime)
    fechatermino = Column(DateTime)
    notas = Column(String(250), nullable=False)
    bl = Column(String(25), nullable=False)
    FUERAPUERTO = Column(Boolean, nullable=False)
    FACTURADO = Column(Boolean, nullable=False)
    FACTURAR = Column(Boolean, nullable=False)
    efechatermino = Column(DateTime)
    pfechainicio = Column(DateTime)
    pfechatermino = Column(DateTime)
    ifechainicio = Column(DateTime)
    TIRExport = Column(String(25), nullable=False)
    TIRImport = Column(String(25), nullable=False)
    OrdenPago = Column(String(25), nullable=False)
    FechaQuedan = Column(DateTime)
    PrecioAgregado = Column(Numeric(18, 6), nullable=False)
    cuenta = Column(Integer, nullable=False)
    pagado = Column(Boolean, nullable=False)
    pagar = Column(Boolean, nullable=False)
    costopago = Column(Numeric(18, 6), nullable=False)
    nosujeto = Column(Numeric(18, 6), nullable=False)
    d1 = Column(Integer)
    d2 = Column(Integer)
    d3 = Column(Integer)
    d4 = Column(Integer)
    d5 = Column(Integer)
    d6 = Column(Integer)
    d7 = Column(Integer)
    d8 = Column(Integer)
    d9 = Column(Integer)
    d10 = Column(Integer)
    d11 = Column(Integer)
    d12 = Column(Integer)
    d13 = Column(Integer)
    d14 = Column(Integer)
    d15 = Column(Integer)
    d16 = Column(Integer)
    d17 = Column(Integer)
    d18 = Column(Integer)
    d19 = Column(Integer)
    d20 = Column(Integer)
    d21 = Column(Integer)
    d22 = Column(Integer)
    d23 = Column(Integer)
    d24 = Column(Integer)
    d25 = Column(Integer)
    d26 = Column(Integer)
    d27 = Column(Integer)
    d28 = Column(Integer)
    d29 = Column(Integer)
    d30 = Column(Integer)
    d31 = Column(Integer)
    mes = Column(Integer, nullable=False)
    ano = Column(Integer, nullable=False)
    nproducto = Column(String(100), nullable=False)
    pauta = Column(Integer, nullable=False)
    PRECIOPROV = Column(Numeric(18, 6), nullable=False)
    FECHAPROV = Column(DateTime)
    OTROSCPROV = Column(Numeric(18, 6), nullable=False)
    intervalopauta = Column(Integer, nullable=False)
    midpfactura = Column(Integer, nullable=False)
    vinculado = Column(Boolean, nullable=False)
    ocCantidad = Column(Numeric(18, 6), nullable=False)
    CantidadFalta = Column(Numeric(18, 6), nullable=False)
    viajeterminado = Column(Boolean, nullable=False)
    NoDocumentoViaje = Column(String(15), nullable=False)
    fechaliquida = Column(DateTime)
    gasto = Column(Numeric(12, 2))
    notagasto = Column(String(250))
    prodprec = Column(Integer)
    usuariogasto = Column(Integer)

    # Relaciones
    # kardex_rel = relationship("Kardex", back_populates="dpfactura_set")  # Comentado automáticamente
    # pfactura_rel = relationship("Pfactura", back_populates="dpfactura_set")  # Comentado automáticamente

    def __repr__(self):
        return "<Dpfactura(dpfactura={self.dpfactura})>"