# Generado automáticamente
# Tabla: dbo.empresa
# Fecha: 2025-05-13 16:44:58

from ..base import Base
from sqlalchemy import Column, Boolean
from sqlalchemy import Column, DateTime
from sqlalchemy import Column, Integer
from sqlalchemy import Column, Numeric
from sqlalchemy import Column, String


class Empresa(Base):
    __tablename__ = "empresa"
    __table_args__ = {"schema": "dbo"}

    numissspat = Column(String(9), nullable=False)
    nempresa = Column(String(55), nullable=False)
    activo = Column(Boolean, nullable=False)
    direccion = Column(String(60), nullable=False)
    telefono1 = Column(String(14), nullable=False)
    telefono2 = Column(String(14), nullable=False)
    fax = Column(String(14), nullable=False)
    registro = Column(String(20), nullable=False)
    dui = Column(String(20), nullable=False)
    nit = Column(String(20), nullable=False)
    representa = Column(String(55), nullable=False)
    giro = Column(String(60), nullable=False)
    municip = Column(Integer, nullable=False)
    empresa = Column(Integer, primary_key=True, nullable=False, autoincrement=True)
    usuario = Column(Integer, nullable=False)
    horatiempo = Column(DateTime, nullable=False)
    pais = Column(Integer, nullable=False)
    MONEDA = Column(Integer, nullable=False)
    elSalvador = Column(Boolean, nullable=False)
    Guatemala = Column(Boolean, nullable=False)
    nicaragua = Column(Boolean, nullable=False)
    honduras = Column(Boolean, nullable=False)
    costarica = Column(Boolean, nullable=False)
    panama = Column(Boolean, nullable=False)
    estadosunidos = Column(Boolean, nullable=False)
    mexico = Column(Boolean, nullable=False)
    chile = Column(Boolean, nullable=False)
    ecuador = Column(Boolean, nullable=False)
    peru = Column(Boolean, nullable=False)
    venezuela = Column(Boolean, nullable=False)
    correlativoQuedan = Column(Integer, nullable=False)
    soloExistencias = Column(Boolean, nullable=False)
    sidomingo = Column(Boolean, nullable=False)
    puertoDescarga = Column(String(35), nullable=False)
    puertoEntrega = Column(String(35), nullable=False)
    email = Column(String(150), nullable=False)
    docunico = Column(Boolean, nullable=False)
    autorizacion = Column(String(25), nullable=False)
    notas = Column(String(350), nullable=False)
    cajanumero = Column(String(100))
    vendedorbodega = Column(Boolean, nullable=False)
    escogerprinter = Column(Boolean, nullable=False)
    preciocaja = Column(Boolean, nullable=False)
    activapermisos = Column(Boolean, nullable=False)
    planilla30 = Column(Boolean, nullable=False)
    isr = Column(Numeric(18, 6), nullable=False)
    aportacionsoli = Column(Numeric(18, 6), nullable=False)
    vistaprevia = Column(Boolean, nullable=False)
    confirmaprint = Column(Boolean, nullable=False)
    justprint = Column(Boolean, nullable=False)
    pcloud = Column(Boolean, nullable=False)
    prefijarcantuno = Column(Integer, nullable=False)
    rembodcaja = Column(Boolean)
    preparapedido = Column(Boolean, nullable=False)
    rutareloj = Column(String(300), nullable=False)
    sipreciocosto = Column(Boolean, nullable=False)
    autosinctipomov = Column(Boolean, nullable=False)
    cuantasListasPrecio = Column(Integer)
    fPercepcion = Column(Integer, nullable=False)
    pPercepcion = Column(Boolean, nullable=False)
    fRetencion = Column(Integer, nullable=False)
    pRetencion = Column(Boolean, nullable=False)
    sinInternet = Column(Boolean, nullable=False)
    sinImpuesto = Column(Boolean, nullable=False)
    fseguridad = Column(Boolean, nullable=False)
    variosprecios = Column(Boolean, nullable=False)
    noselectPrint = Column(Integer, nullable=False)
    precioenCompra = Column(Boolean, nullable=False)
    manejaLote = Column(Boolean, nullable=False)
    ppistola = Column(Boolean, nullable=False)
    escoje_precio = Column(Boolean, nullable=False)
    busca_por_registro = Column(Boolean, nullable=False)
    bonifica = Column(Boolean, nullable=False)
    descxvol = Column(Boolean, nullable=False)
    escalzado = Column(Boolean, nullable=False)
    PrecioCompcIva = Column(Boolean, nullable=False)
    esdefinitiva = Column(Boolean, nullable=False)
    cuantosPrint = Column(Integer, nullable=False)
    vretencion = Column(Boolean, nullable=False)
    vpercepcion = Column(Boolean, nullable=False)
    siCantidad = Column(Boolean, nullable=False)
    blockcprecio = Column(Boolean, nullable=False)
    blockCliRapido = Column(Boolean, nullable=False)
    llevacxp = Column(Boolean, nullable=False)
    cambiaPrecios = Column(Boolean, nullable=False)
    pcontrolexist = Column(Boolean, nullable=False)
    descxval = Column(Boolean, nullable=False)
    offline = Column(Boolean, nullable=False)
    consigna = Column(Boolean, nullable=False)
    solocontado = Column(Boolean, nullable=False)
    solocredito = Column(Boolean, nullable=False)
    solof2 = Column(Boolean, nullable=False)
    cambiaLprecio = Column(Boolean, nullable=False)
    cdespacho = Column(Boolean, nullable=False)
    lockvendedor = Column(Boolean, nullable=False)
    obligaclave = Column(Boolean, nullable=False)
    mesobligaclave = Column(Integer, nullable=False)
    tasaInteres = Column(Numeric(5, 2), nullable=False)
    preservado = Column(Boolean, nullable=False)
    factor_fob = Column(Numeric(5, 2), nullable=False)
    a90 = Column(Boolean, nullable=False)
    boniplus = Column(Boolean, nullable=False)
    iglesia = Column(Boolean, nullable=False)
    cambioacero = Column(Boolean, nullable=False)
    esfactor = Column(Boolean, nullable=False)
    gestionventa = Column(Integer, nullable=False)
    dirFactura = Column(String(250))
    margenPrecio = Column(Boolean, nullable=False)
    tipo = Column(Integer)
    conemail = Column(Boolean, nullable=False)

    def __repr__(self):
        return "<Empresa(empresa={self.empresa})>"