# Generado automáticamente
# Tabla: dbo.ocompra
# Fecha: 2025-05-13 16:44:58

from ..base import Base
from sqlalchemy import Column, Boolean
from sqlalchemy import Column, DateTime
from sqlalchemy import Column, Integer
from sqlalchemy import Column, Numeric
from sqlalchemy import Column, String


class Ocompra(Base):
    __tablename__ = "ocompra"
    __table_args__ = {"schema": "dbo"}

    activo = Column(Boolean, nullable=False)
    nula = Column(Boolean, nullable=False)
    impresa = Column(Boolean, nullable=False)
    enfirme = Column(Boolean, nullable=False)
    contabilidad = Column(Boolean, nullable=False)
    tipomov = Column(Integer, nullable=False)
    numedocu = Column(String(9), nullable=False)
    pedido = Column(String(10), nullable=False)
    fecha = Column(DateTime, nullable=False)
    tipovta = Column(Integer, nullable=False)
    encompra = Column(Integer, nullable=False)
    proveedor = Column(Integer, nullable=False)
    proveedor2 = Column(Integer, nullable=False)
    condpago = Column(Integer, nullable=False)
    iva = Column(Integer, nullable=False)
    cprodprec = Column(Integer, nullable=False)
    moneda = Column(Integer, nullable=False)
    tasacambio = Column(Numeric(16, 6), nullable=False)
    tasacambioseg = Column(Numeric(16, 6), nullable=False)
    tasacambiotres = Column(Numeric(16, 6), nullable=False)
    exenta = Column(Numeric(16, 6), nullable=False)
    afecta = Column(Numeric(16, 6), nullable=False)
    viva = Column(Numeric(16, 6), nullable=False)
    tax = Column(Numeric(16, 6), nullable=False)
    descuentos = Column(Numeric(16, 6), nullable=False)
    descaplica = Column(Boolean, nullable=False)
    flete = Column(Numeric(16, 6), nullable=False)
    fob = Column(Numeric(16, 6), nullable=False)
    seguro = Column(Numeric(16, 6), nullable=False)
    monto = Column(Numeric(16, 6), nullable=False)
    montcomp = Column(Numeric(16, 6), nullable=False)
    montgasto = Column(Numeric(16, 6), nullable=False)
    montbonif = Column(Numeric(16, 6), nullable=False)
    pdesc = Column(Numeric(16, 6), nullable=False)
    vdesc = Column(Numeric(16, 6), nullable=False)
    notas = Column(String(400))
    ocompra = Column(Integer, primary_key=True, nullable=False, autoincrement=True)
    empresa = Column(Integer, nullable=False)
    usuario = Column(Integer, nullable=False)
    horatiempo = Column(DateTime, nullable=False)
    fovial = Column(Numeric(16, 6), nullable=False)
    rfecha = Column(DateTime)
    rnumedocu = Column(String(9), nullable=False)
    compra = Column(Integer, nullable=False)
    rmontcomp = Column(Numeric(16, 6), nullable=False)
    pagada = Column(Boolean, nullable=False)
    pfecha = Column(DateTime)
    proyecto = Column(Integer, nullable=False)
    caja = Column(Integer, nullable=False)
    bodega = Column(Integer, nullable=False)
    fechaDespacho = Column(DateTime)
    fechaRecepcion = Column(DateTime)
    retencion = Column(Numeric(18, 6), nullable=False)
    percepcion = Column(Numeric(18, 6), nullable=False)
    contenedor = Column(String(15), nullable=False)
    vcartacredito = Column(Numeric(18, 6), nullable=False)
    vpagocredito = Column(Numeric(18, 6), nullable=False)
    vpagocontado = Column(Numeric(18, 6), nullable=False)
    vdeposito = Column(Numeric(18, 6), nullable=False)
    cartacredito = Column(Boolean, nullable=False)
    pagocredito = Column(Boolean, nullable=False)
    pagocontado = Column(Boolean, nullable=False)
    deposito = Column(Boolean, nullable=False)
    notasPago = Column(String(350), nullable=False)
    transpte = Column(Integer, nullable=False)
    embarque = Column(Integer, nullable=False)
    cembarque = Column(Integer, nullable=False)
    pdesc1 = Column(Numeric(5, 2), nullable=False)
    pdesc2 = Column(Numeric(5, 2), nullable=False)
    pdesc3 = Column(Numeric(5, 2), nullable=False)
    pdesc4 = Column(Numeric(5, 2), nullable=False)
    pdesc5 = Column(Numeric(5, 2), nullable=False)
    pdesc6 = Column(Numeric(5, 2), nullable=False)
    cuota1 = Column(Numeric(18, 6), nullable=False)
    cuota2 = Column(Numeric(18, 6), nullable=False)
    cuota3 = Column(Numeric(18, 6), nullable=False)
    carta = Column(Numeric(18, 6), nullable=False)
    cartaCred = Column(Numeric(18, 6), nullable=False)
    otra = Column(Numeric(18, 6), nullable=False)
    fdevolucion1 = Column(DateTime)
    fdevolucion2 = Column(DateTime)
    fdevolucion3 = Column(DateTime)
    fdevolucion4 = Column(DateTime)
    fdevolucion5 = Column(DateTime)
    fentrega1 = Column(DateTime)
    fentrega2 = Column(DateTime)
    fentrega3 = Column(DateTime)
    fentrega4 = Column(DateTime)
    fentrega5 = Column(DateTime)
    micaja1 = Column(String(250), nullable=False)
    micaja2 = Column(String(250), nullable=False)
    loadingcontainer = Column(String(120), nullable=False)
    billloading = Column(String(35), nullable=False)
    containerno = Column(String(35), nullable=False)
    marchamo = Column(String(35), nullable=False)
    loadingPort = Column(String(35), nullable=False)
    DischargePort = Column(String(35), nullable=False)
    DeliveryPort = Column(String(35), nullable=False)
    hechoen = Column(String(25), nullable=False)
    deliveryterms = Column(String(80), nullable=False)
    ctracking = Column(Integer, nullable=False)
    doccompra = Column(String(6), nullable=False)
    fechacompra = Column(DateTime)
    recinto = Column(Boolean, nullable=False)
    metros3 = Column(Numeric(18, 6), nullable=False)
    metros3p = Column(Numeric(18, 6), nullable=False)
    fecharecinto = Column(DateTime)
    impuesto = Column(Numeric(18, 6), nullable=False)
    impuestop = Column(Numeric(18, 6), nullable=False)
    arancel = Column(Numeric(18, 6), nullable=False)
    arancelp = Column(Numeric(18, 6), nullable=False)
    cif = Column(Numeric(18, 6), nullable=False)
    montoiva = Column(Numeric(18, 6), nullable=False)
    polisa = Column(Integer, nullable=False)
    ndeposito = Column(Integer, nullable=False)
    recintofiscal = Column(Integer, nullable=False)
    poliza = Column(String(25), nullable=False)

    def __repr__(self):
        return "<Ocompra(ocompra={self.ocompra})>"